### ISSUE TITLE
ConcurrentModificationException still present

### ISSUE THREAD

**Issue by juan3036** [unicesi/pascani#9]
Hi @jachinte 

I have some bad news, the concurrentmodificationexception that we had discussed a time ago, it is still present in Pascani, the exception is raised when you are traying to fetch the events from the external probe. I add a pastebin link to the exception. [http://pastebin.com/Vfz0y7rC](url)

One question, the last version of Amelia allows to deploy a component in a subsystem but shutdown from another??

Thanks

**Comment by jachinte** [comment]
Hi @juan3036! sorry for the delay.

It seems like #8 should be re-opened.

On your question, I'm moving it to a [new issue](https://github.com/unicesi/amelia/issues/10) in the corresponding repository.
